stages:
  - build

build_image:
  stage: build
  script:
    - ls -la
    - cd src
    - npm install
    - npm run build
    - cd ..
    - CI_COMMIT_TAG=`git log | grep -e "^commit.*" | wc -l`
    - docker build --pull -t "$DOCKER_REGISTRY_URL"/"$DOCKER_IMAGE_GROUP"/xsfe_v2:"$CI_COMMIT_TAG" .
    - docker push "$DOCKER_REGISTRY_URL"/"$DOCKER_IMAGE_GROUP"/xsfe_v2:"$CI_COMMIT_TAG"
    - docker rmi "$DOCKER_REGISTRY_URL"/"$DOCKER_IMAGE_GROUP"/xsfe_v2:"$CI_COMMIT_TAG"

  only:
    - master
  tags:
    - abc